accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'


urlpatterns = [
    path('login/', views.login_request, name='login'),
    path('logout/', views.logout_request, name='logout'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('profile/', views.update_profile, name='update_profile'),
    path('message/', views.message_mentor, name='message_mentor'),
]

main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('categories/', views.categories, name='categories'),
    path('categories/<slug:slug>/', views.category_guides, name='category_guides'),
    path('guides/<slug:slug>/', views.specific_guide, name='specific_guide'),
]

mentee/urls.py
from django.urls import path
from . import views

app_name = 'mentee'


urlpatterns = [
    # path('', views.dashboard, name='dashboard'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('accounts/', include('accounts.urls')),
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
# from tinymce import HTMLField


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name='username')
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField(max_length=50, verbose_name='your email', help_text='Enter your active email address')
    phone = models.CharField(max_length=15, verbose_name='your phone number')
    interest = models.CharField(max_length=200, verbose_name='your interests')
    code_goal = models.TextField(verbose_name='your coding goal')

    def __str__(self):
        return self.user.username


class Project(models.Model):
    title = models.CharField(max_length=200)
    summary = models.CharField(max_length=200)
    live_project_link = models.URLField(max_length=200)
    codebase_link = models.URLField(max_length=200)
    description = models.TextField()
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title



class Chat(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    subject = models.CharField(max_length=100)
    # message = HTMLField('Content Message')
    message = models.TextField()

    def __str__(self):
        return self.subject

main/models.py
from django.db import models
from django.utils import timezone


class Category(models.Model):
    name = models.CharField(max_length=200)
    summary = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200)

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name


class Guide(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    published_date = models.DateTimeField(default=timezone.now)
    category = models.ForeignKey(Category, default=1, on_delete=models.SET_DEFAULT)
    slug = models.SlugField(max_length=200)
    active = models.BooleanField(default=False)

    def is_active(self):
        self.active = True

    def __str__(self):
        return self.title

accounts/forms.py
from django import forms
from .models import Profile, Chat
from tinymce import TinyMCE 


class ProfileForm(forms.ModelForm):
    # user = forms.CharField(help_text='This field cannot be changed!', widget=forms.TextInput(attrs={'readonly':'readonly'}))

    class Meta:
        model = Profile
        fields = ['first_name', 'last_name', 'email', 'phone', 'interest', 'code_goal']
        # fields = '__all__'
        # exclude = ['user']


class ChatForm(forms.ModelForm):
    class Meta:
        model = Chat
        fields = ['subject', 'message']

        
        

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import logout, authenticate, login
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .models import Profile, Project
from .forms import ProfileForm, ChatForm


def login_request(request):
    if request.method == 'POST':
        form = AuthenticationForm(request=request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.success(request, f"You are now logged in as {username}")
                return redirect('main:homepage')
            else:
                messages.error(request, "Invalid username or password.")
        else:
            messages.error(request, "Invalid username or password.")
    form = AuthenticationForm()

    context = {
        'form': form
    }
    return render(request, 'accounts/login.html', context)


def logout_request(request):
    logout(request)
    messages.info(request, "You've logged out successfully")
    return redirect('accounts:login')


@login_required(login_url='accounts:login')
def dashboard(request):
    current_user = request.user
    try:
        user_profile = current_user.profile
    except Profile.DoesNotExist:
        user_profile = None
    user_projects = current_user.project_set.all()

    context = {
        'user_profile': user_profile,
        'user_projects': user_projects
    }
    return render(request, 'accounts/dashboard.html', context)


def update_profile(request):
    try:
        user_profile = request.user.profile
    except Profile.DoesNotExist:
        user_profile = Profile(user=request.user)

    if request.method == 'POST':
        form = ProfileForm(data=request.POST, instance=user_profile)
        if form.is_valid():
            form.save()
            messages.info(request, "You have successfully updated your profile")
            return redirect('accounts:dashboard')
    else:
        form = ProfileForm(instance=user_profile)

    context = {
        'form': form
    }
    return render(request, 'accounts/update_profile.html', context)


@login_required(login_url='accounts:login')
def message_mentor(request):
    if request.method == 'POST':
        form = ChatForm(data=request.POST)
        if form.is_valid():
            chat = form.save(commit=False)
            chat.author = request.user
            chat.save()
            messages.info(request, "Your message has been sent.")
            return redirect('accounts:dashboard')
        else:
            messages.error(request, "You have missed out required fields")
    else:
        form = ChatForm()
     
    context = {
        'form': form
    }
    return render(request, 'accounts/message_mentor.html', context)

main/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Guide
from django.contrib.auth.decorators import login_required


@login_required(login_url='accounts:login')
def homepage(request):
    return render(request, 'main/homepage.html')


@login_required(login_url='accounts:login')
def categories(request):
    categories = Category.objects.all()
    context = {
        "categories": categories
    }
    return render(request, 'main/categories.html', context)


@login_required(login_url='accounts:login')
def category_guides(request, slug):
    category = get_object_or_404(Category, slug=slug)
    category_guides = category.guide_set.all()
    # category_guides = get_object_or_404(Category, slug=slug).guide_set.all()
    context = {
        'category_guides': category_guides
    }
    return render(request, 'main/category_guides.html', context)
    

@login_required(login_url='accounts:login')
def specific_guide(request, slug):
    guide = get_object_or_404(Guide, slug=slug)

    # tutorials_from_series = Guide.objects.filter(category__name=guide.category).order_by('published_date')
    guides_from_category = Guide.objects.filter(category=guide.category).order_by('published_date')

    context = {
        'guide': guide,
        'sidebar': guides_from_category,
    }
    return render(request, 'main/specific_guide.html', context)
    

accounts/templates/accounts/dashboard.html
{% extends 'main/base.html' %}

{% block content %}
<h3>Your Dashboard:</h3>
<hr>
<hr>
<div>
    <h5>Your Profile:</h5>
    {% if user_profile is None %}
        <p>You have no profile yet. Click on the link below to create it.</p>
    {% else %}
        <ul>
            <li><strong>Username:</strong> {{ user_profile.user }}</li>
            <li><strong>Full name:</strong> {{ user_profile.first_name }} {{ user_profile.last_name }}</li>
            <li><strong>Email:</strong> {{ user_profile.email }}</li>
            <li><strong>Phone:</strong> {{ user_profile.phone }}</li>
            <li><strong>Interest:</strong> {{ user_profile.interest }}</li>
            <li><strong>Code Goal:</strong> {{ user_profile.code_goal }}</li>
        </ul>
    {% endif %}
    <a class="btn btn-outline-primary" href="{% url 'accounts:update_profile' %}">Update Profile<i class="material-icons right">update</i></a>
</div>
<br>
<hr>
<div>
    <h5>Your Projects:</h5>
    {% for obj in user_projects %}
    <ol>
        <li>{{ obj.title }}</li>
    </ol>
    {% empty %}
        <p>You have no projects yet. Click on the link below to create some.</p>
    {% endfor %}
    <a class="btn btn-outline-primary" href="#">Add Projects<i class="material-icons right">add_to_queue</i></a>
</div>
<br>
<hr>
<div>
    <h5>Your Message Board:</h5>
    <a class="btn btn-outline-primary" href="{% url 'accounts:message_mentor' %}">Send Message<i class="material-icons right">send</i></a>
</div>
<br>
<hr>
{% endblock %}

accounts/templates/accounts/login.html
<head>
  {% load static %}
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0"/>
  <title>MentorMeCode - Login</title>

  <!-- CSS  -->
  <!-- Prism CSS -->
  <link href="{% static 'tinymce/css/prism.css' %}" rel="stylesheet">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link href="{% static 'main/css/style.css' %}" type="text/css" rel="stylesheet" media="screen,projection"/>
<!-- Compiled and minified CSS -->
  <link href="{% static 'main/css/materialize.css' %}" rel="stylesheet" media="screen,projection">
  <!-- Compiled and minified JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>
<body>


  <div class="container">
    <br><br><br>
    {% include 'main/partials/messaging.html' %}
    {% block content %}

        <div class="container">
            <form method="POST">
            {% csrf_token %}
            {{form.as_p}}
                <button style="background-color:#F4EB16; color:blue" class="btn btn-outline-info" type="submit">Login</button>
            </form>
            Don't have an account? <a href="#"><strong>register here</strong></a>!
        </div>
    {% endblock %}
    <br><br>
  </div>

  <!--  Scripts-->
  <!-- Prism JS -->
  <script src="{% static 'tinymce/js/prism.js' %}"></script>
  <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
  <!-- <script src="{% static 'main/js/materialize.js' %}"></script> -->
  <script src="{% static 'main/js/init.js' %}"></script>
  <script>M.AutoInit();</script>
  {% block script %}{% endblock %}
  </body>
</html>

accounts/templates/accounts/message_mentor.html
{% extends 'main/base.html' %}

{% block content %}
<h3>Message Your Mentor:</h3>
<br>
<div>
    <form method="POST" action=".">{% csrf_token %}
        {{ form.as_p }}
        <p>
            <button class="btn waves-effect waves-light" type="submit" name="action">Send
                <i class="material-icons right">send</i>
            </button>   
            <a style="background-color: red" class="btn btn-outline-primary" href="{% url 'accounts:dashboard' %}">Cancel<i class="material-icons right">cancel</i></a>
        </p>
    </form>
</div>

{% endblock %}

accounts/templates/accounts/register.html
{% extends 'main/base.html' %}
{% block title %}Register{% endblock %}
{% block content %}
    <br>
    <form method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <button style="background-color:#F4EB16; color:blue" class="btn btn-outline-info" type="submit">Sign Up</button>
    </form>

    If you already have an account <a href="/login" target="blank"><strong>login</strong></a> instead.

{% endblock %}

accounts/templates/accounts/update_profile.html
{% extends 'main/base.html' %}

{% block content %}
<h3>Update Your Profile:</h3>
<br>
<div>
    <form method="POST" action=".">{% csrf_token %}
        {{ form.as_p }}
        <p>
            <button class="btn waves-effect waves-light" type="submit" name="action">Update
                <i class="material-icons right">update</i>
            </button>   
            <a style="background-color: red" class="btn btn-outline-primary" href="{% url 'accounts:dashboard' %}">Cancel<i class="material-icons right">cancel</i></a>
        </p>
    </form>
</div>

{% endblock %}

main/templates/main/categories.html
{% extends 'main/base.html' %}

{% block content %}

    <div class="row">
        {% for obj in categories %}
            <div class="col s12 m6 l4">
                <a href="{% url 'main:category_guides' slug=obj.slug %}", style="color:#000">
                    <div class="card hoverable">
                        <div class="card-content">
                            <div class="card-title">{{ obj.name }}</div>
                            <p>{{ obj.summary }}</p>
                        </div>
                    </div>
                </a>
            </div>
        {% endfor %}
    </div>
{% endblock %}

main/templates/main/category_guides.html
{% extends 'main/base.html' %}

{% block content %}

    <div class="row">
        {% for obj in category_guides %}
            <div class="col s12 m6 l4">
                <a href="{% url 'main:specific_guide' slug=obj.slug %}", style="color:#000">
                    <div class="card hoverable">
                        <div class="card-content">
                            <div class="card-title">{{obj.title}}</div>
                            <p></p>
                        </div>
                    </div>
                </a>
            </div>
        {% empty %}
            <div class="container">
                <p>No content here</p>
            </div>
        {% endfor %}
    </div>
{% endblock %}

main/templates/main/error.html
{% extends 'main/base.html' %}

{% block content %}
  <div class="container" align="left">
    <img src="#">
  </div>
  <div class="container" align="left">
    <h4>404 Snake says hi. Your Page was not found.</h4>
    <p>This error has been logged and will be reviewed.</p> 
    <p>Feel free to contact Raymond@MentorMeCode.com for help!</p>
    <p><a class="btn btn-primary btn-lg" onclick="goBack()" role="button">Go Back!</a></p>
  </div>

{% endblock %}
{% block script %}
<script>
    function goBack() {
        window.history.back()
    }
</script>
{% endblock %}

main/templates/main/home.html
{% extends 'main/header.html' %}

{% block content %}
<div class="row">
    {% for tut in tutorials %}
        <div class="col s12 m6">
          <div class="card hoverable">
            <div class="card-content">
              <span class="card-title">{{tut.title}}</span>
              <p style="font-size: 70%">Published {{tut.published}}</p>
              <p>{{tut.content|safe}}</p>
            </div>
          </div>
        </div>
    {% endfor %}
</div>
{% endblock %}

main/templates/main/homepage.html
{% extends 'main/base.html' %}
{% block content %}
  <div class="section no-pad-bot" id="index-banner">
    <div class="container">
      <br><br>
      <h1 class="header center orange-text">Mentor Me Code</h1>
      <div class="row center">
        <h5 class="header col s12 light">A modern approach to mentoring newbies master coding to solve problems and create</h5>
      </div>
      <div class="row center">
        <a href="{% url 'main:categories' %}" id="download-button" class="btn-large waves-effect waves-light orange">Get Started</a>
      </div>
      <br><br>

    </div>
  </div>


  <div class="container">
    <div class="section">

      <!--   Icon Section   -->
      <div class="row">
        <div class="col s12 m4">
          <div class="icon-block">
            <h2 class="center light-blue-text"><i class="material-icons">flash_on</i></h2>
            <h5 class="center">Speeds up development</h5>

            <p class="light"></p>
          </div>
        </div>

        <div class="col s12 m4">
          <div class="icon-block">
            <h2 class="center light-blue-text"><i class="material-icons">group</i></h2>
            <h5 class="center">User Experience Focused</h5>

            <p class="light"></p>
          </div>
        </div>

        <div class="col s12 m4">
          <div class="icon-block">
            <h2 class="center light-blue-text"><i class="material-icons">settings</i></h2>
            <h5 class="center">Easy to work with</h5>

            <p class="light"></p>
          </div>
        </div>
      </div>

    </div>
    <br><br>
  </div>

{% endblock %}
  

main/templates/main/includes/messages.html
{% if messages %}
    {% for message in messages %}
        {% if message.tags == 'success'%}
            <script>M.toast({html: "{{message}}", classes: 'green rounded', displayLength:2000});</script>
        {% elif message.tags == 'info'%}
            <script>M.toast({html: "{{message}}", classes: 'blue rounded', displayLength:2000});</script>
        {% elif message.tags == 'warning'%}
            <script>M.toast({html: "{{message}}", classes: 'orange rounded', displayLength:10000});</script>
        {% elif message.tags == 'error'%}
            <script>M.toast({html: "{{message}}", classes: 'red rounded', displayLength:10000});</script>
        {% endif %}
    {% endfor %}
{% endif %}

main/templates/main/login.html
{% extends 'main/base.html' %}

{% block content %}

    <div class="container">
        <form method="POST">
        {% csrf_token %}
        {{form.as_p}}
            <button style="background-color:#F4EB16; color:blue" class="btn btn-outline-info" type="submit">Login</button>
        </form>
        Don't have an account? <a href="/register" target="blank"><strong>register here</strong></a>!
    </div>
{% endblock %}

main/templates/main/partials/footer.html
  <!-- <footer class="page-footer orange"> -->
  <footer class="page-footer">
    <div class="container">
      <div class="row">
        <div class="col l6 s12">
          <h5 class="white-text">About MentorMeCode</h5>
          <p class="grey-text text-lighten-4">MentorMeCode is an ongoing platform where we take a top-bottom approach as opposed to the norm of bottom-up style. From web development to machine learning (AI) to data science to tinkering with robotics and the raspberry pi.</p>


        </div>
        <div class="col l3 s12">
          <h5 class="white-text">Settings</h5>
          <ul>
            <li><a class="white-text" href="#!">Link 1</a></li>
            <li><a class="white-text" href="#!">Link 2</a></li>
            <li><a class="white-text" href="#!">Link 3</a></li>
            <li><a class="white-text" href="#!">Link 4</a></li>
          </ul>
        </div>
        <div class="col l3 s12">
          <h5 class="white-text">Connect</h5>
          <ul>
            <li><a class="white-text" href="#!">Link 1</a></li>
            <li><a class="white-text" href="#!">Link 2</a></li>
            <li><a class="white-text" href="#!">Link 3</a></li>
            <li><a class="white-text" href="#!">Link 4</a></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="footer-copyright">
      <div class="container">
      &copy; 2020 MentorMeCode. Made with love by <a class="text-lighten-3" href="#!">MentorMeCode</a>.
      </div>
    </div>
  </footer>

main/templates/main/partials/navbar.html
<!-- <div class="navbar-fixed"> -->
  <nav class="lighten-1 fixed" role="navigation">
    <div class="nav-wrapper container"><a id="logo-container" href="{% url 'main:homepage' %}" class="brand-logo">MentorMeCode</a>
      <ul class="right hide-on-med-and-down">
        <li><a href="/">Home</a></li>
        {% if user.is_authenticated %}
          <li><a href="{% url 'accounts:dashboard' %}">Dashboard</a></li>
          <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
          <li><a href="{% url 'accounts:message_mentor' %}">Message</a></li>
        {% else %}
          <li><a href="{% url 'accounts:login' %}">Login</a></li>
          <!-- <li><a href="#">Register</a></li> -->
        {% endif %}
      </ul>

      <ul id="nav-mobile" class="sidenav">
        <li><a href="/">Home</a></li>
        {% if user.is_authenticated %}
          <li><a href="{% url 'accounts:dashboard' %}">Dashboard</a></li>
          <li><a href="{% url 'accounts:message_mentor' %}">Message</a></li>
          <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
        {% else %}
          <li><a href="{% url 'accounts:login' %}">Login</a></li>
          <!-- <li><a href="#">Register</a></li> -->
        {% endif %}
      </ul>
      <a href="#" data-target="nav-mobile" class="sidenav-trigger"><i class="material-icons">menu</i></a>
    </div>
  </nav>
<!-- </div> -->

main/templates/main/specific_guide.html
{% extends 'main/base.html' %}

{% block content %}

    <div class="row">

        <div class="col s12, m8, l8">
            <h4>{{ guide.title }}</h4>
            <p style="font-size:70%">Published {{ guide.published_date }}</p>
            {{ guide.content|safe }}
        </div>

        <div class="col s12 m4 l4">
            <ul class="collapsible popout">
                {% for obj in sidebar %}
                    {% if guide.title == obj.title %}
                        <li class="active">
                            <div class="collapsible-header">{{ obj.title }}<br>(currently viewing)</div>
                        </li>
                    {% else %}
                        <li>
                            <div class="collapsible-header">{{obj.title}}</div>
                            <div class="collapsible-body">
                                <p><a href="{% url 'main:specific_guide' slug=obj.slug %}"><button class="btn waves-effect waves-light right-align" style="background-color:yellow; color:black">Go</button></a></p>

                            </div>
                        </li>
                    {% endif %}
                {% endfor %}
            </ul>
        </div>

    </div>

{% endblock %}

main/templates/main/tutorial.html
{% extends 'main/base.html' %}

{% block content %}

    <div class="row">

        <div class="col s12, m8, l8">
            <h3>{{tutorial.title}}</h3>
            <p style="font-size:70%">Published {{tutorial.published}}</p>
            {{tutorial.content|safe}}
        </div>

        <div class="col s12 m4 l4">
            <ul class="collapsible popout">
                {% for tutorial in sidebar %}
                    {% if forloop.counter0 == this_tut_idx %}
                        <li class="active">
                            <div class="collapsible-header">{{tutorial.title}}<br>(currently viewing)</div>
                        </li>
                    {% else %}
                        <li>
                            <div class="collapsible-header">{{tutorial.title}}</div>
                            <div class="collapsible-body">
                                <p><a href="/{{tutorial.slug}}"><button class="btn waves-effect waves-light right-align" style="background-color:yellow; color:black">Go</button></a></p>

                            </div>
                        </li>
                    {% endif %}
                {% endfor %}
            </ul>
        </div>

    </div>

{% endblock %}

templates/accounts/dashboard.html
{% extends 'base.html' %}

{% block content %}
<h3>Your Dashboard:</h3>
<hr>
<hr>
<div>
    <h5>Your Profile:</h5>
    {% if user_profile is None %}
        <p>You have no profile yet. Click on the link below to create it.</p>
    {% else %}
        <ul>
            <li><strong>Username:</strong> {{ user_profile.user }}</li>
            <li><strong>Full name:</strong> {{ user_profile.first_name }} {{ user_profile.last_name }}</li>
            <li><strong>Email:</strong> {{ user_profile.email }}</li>
            <li><strong>Phone:</strong> {{ user_profile.phone }}</li>
            <li><strong>Interest:</strong> {{ user_profile.interest }}</li>
            <li><strong>Code Goal:</strong> {{ user_profile.code_goal }}</li>
        </ul>
    {% endif %}
    <a class="btn btn-outline-primary" href="{% url 'accounts:update_profile' %}">Update Profile<i class="material-icons right">update</i></a>
</div>
<br>
<hr>
<div>
    <h5>Your Projects:</h5>
    {% for obj in user_projects %}
    <ol>
        <li>{{ obj.title }}</li>
    </ol>
    {% empty %}
        <p>You have no projects yet. Click on the link below to create some.</p>
    {% endfor %}
    <a class="btn btn-outline-primary" href="#">Add Projects<i class="material-icons right">add_to_queue</i></a>
</div>
<br>
<hr>
<div>
    <h5>Your Message Board:</h5>
    <a class="btn btn-outline-primary" href="{% url 'accounts:message_mentor' %}">Send Message<i class="material-icons right">send</i></a>
</div>
<br>
<hr>
{% endblock %}

templates/main/categories.html
{% extends 'base.html' %}

{% block content %}

    <div class="row">
        {% for obj in categories %}
            <div class="col s12 m6 l4">
                <a href="{% url 'main:category_guides' slug=obj.slug %}", style="color:#000">
                    <div class="card hoverable">
                        <div class="card-content">
                            <div class="card-title">{{ obj.name }}</div>
                            <p>{{ obj.summary }}</p>
                        </div>
                    </div>
                </a>
            </div>
        {% endfor %}
    </div>
{% endblock %}

templates/main/category_guides.html
{% extends 'base.html' %}

{% block content %}

    <div class="row">
        {% for obj in category_guides %}
            <div class="col s12 m6 l4">
                <a href="{% url 'main:specific_guide' slug=obj.slug %}", style="color:#000">
                    <div class="card hoverable">
                        <div class="card-content">
                            <div class="card-title">{{obj.title}}</div>
                            <p></p>
                        </div>
                    </div>
                </a>
            </div>
        {% empty %}
            <div class="container">
                <p>No content here</p>
            </div>
        {% endfor %}
    </div>
{% endblock %}

templates/main/homepage.html
{% extends 'base.html' %}
{% block content %}
  <div class="section no-pad-bot" id="index-banner">
    <div class="container">
      <br><br>
      <h1 class="header center orange-text">Mentor Me Code</h1>
      <div class="row center">
        <h5 class="header col s12 light">A modern approach to mentoring newbies master coding to solve problems and create</h5>
      </div>
      <div class="row center">
        <a href="{% url 'main:categories' %}" id="download-button" class="btn-large waves-effect waves-light orange">Get Started</a>
      </div>
      <br><br>

    </div>
  </div>


  <div class="container">
    <div class="section">

      <!--   Icon Section   -->
      <div class="row">
        <div class="col s12 m4">
          <div class="icon-block">
            <h2 class="center light-blue-text"><i class="material-icons">flash_on</i></h2>
            <h5 class="center">Speeds up development</h5>

            <p class="light"></p>
          </div>
        </div>

        <div class="col s12 m4">
          <div class="icon-block">
            <h2 class="center light-blue-text"><i class="material-icons">group</i></h2>
            <h5 class="center">User Experience Focused</h5>

            <p class="light"></p>
          </div>
        </div>

        <div class="col s12 m4">
          <div class="icon-block">
            <h2 class="center light-blue-text"><i class="material-icons">settings</i></h2>
            <h5 class="center">Easy to work with</h5>

            <p class="light"></p>
          </div>
        </div>
      </div>

    </div>
    <br><br>
  </div>

{% endblock %}
  

templates/main/specific_guide.html
{% extends 'base.html' %}

{% block content %}

    <div class="row">

        <div class="col s12, m8, l8">
            <h4>{{ guide.title }}</h4>
            <p style="font-size:70%">Published {{ guide.published_date }}</p>
            {{ guide.content|safe }}
        </div>

        <div class="col s12 m4 l4">
            <ul class="collapsible popout">
                {% for obj in sidebar %}
                    {% if guide.title == obj.title %}
                        <li class="active">
                            <div class="collapsible-header">{{ obj.title }}<br>(currently viewing)</div>
                        </li>
                    {% else %}
                        <li>
                            <div class="collapsible-header">{{obj.title}}</div>
                            <div class="collapsible-body">
                                <p><a href="{% url 'main:specific_guide' slug=obj.slug %}"><button class="btn waves-effect waves-light right-align" style="background-color:yellow; color:black">Go</button></a></p>

                            </div>
                        </li>
                    {% endif %}
                {% endfor %}
            </ul>
        </div>

    </div>

{% endblock %}

templates/partials/navbar.html
<!-- <div class="navbar-fixed"> -->
  <nav class="lighten-1 fixed" role="navigation">
    <div class="nav-wrapper container"><a id="logo-container" href="{% url 'main:homepage' %}" class="brand-logo">MentorMeCode</a>
      <ul class="right hide-on-med-and-down">
        <!-- <li><a href="/">Home</a></li> -->
        {% if user.is_authenticated %}
          <li><a href="/">Home</a></li>
          <li><a href="{% url 'accounts:dashboard' %}">Dashboard</a></li>
          <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
          <li><a href="{% url 'accounts:message_mentor' %}">Message</a></li>
        {% else %}
          <li><a href="{% url 'accounts:login' %}">Login</a></li>
          <li><a href="#">Register</a></li>
        {% endif %}
      </ul>

      <ul id="nav-mobile" class="sidenav">
        <!-- <li><a href="/">Home</a></li> -->
        {% if user.is_authenticated %}
          <li><a href="/">Home</a></li>
          <li><a href="{% url 'accounts:dashboard' %}">Dashboard</a></li>
          <li><a href="{% url 'accounts:message_mentor' %}">Message</a></li>
          <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
        {% else %}
          <li><a href="{% url 'accounts:login' %}">Login</a></li>
          <li><a href="#">Register</a></li>
        {% endif %}
      </ul>
      <a href="#" data-target="nav-mobile" class="sidenav-trigger"><i class="material-icons">menu</i></a>
    </div>
  </nav>
<!-- </div> -->